### ISSUE TITLE
学习代码时遇到的困惑

### ISSUE THREAD

**Issue by XiaoboD** [XuZhixuan/reporter-2020-04#1]
我想学一下这套代码，有几个地方没太看懂
1. https://secure.eeyes.xyz/reporter/ 这个网站是什么？为什么会有模板数据
2. 怎么知道用户信息可以在 http://jkrb.xjtu.edu.cn/EIP/api/getUserAttribute.htm 网站获取，即平常使用时接触不到的界面你是怎么知道的？

另外，对于这些内容，大佬有推荐的教程吗？我自己找的 python 教程不涉及这些东西

**Comment by XuZhixuan** [comment]
很抱歉才看到这个Issue，关于这两个问题：
1) eeyes.xyz 是我自己注册的网站域名，模板信息和填充数据都是我自己生成上传的。
2) 使用浏览器的开发者工具抓取网络流量，比如在使用 Google Chrome 打开网页后按下 F12 打开 DevTools：
![image](https://user-images.githubusercontent.com/24605014/120887457-8f961780-c625-11eb-8ebf-b73cd5fa0e72.png)
在其中的 Network 选项卡里可以看到网站发出的所有请求数据，借此可以分析网站的运行逻辑。
关于教程因为我本身做后端开发比较多，所以在学习后端开发的时候学到了这些知识，如果想要学习，可以考虑查阅 Python 爬虫的相关书籍。

**Comment by XiaoboD** [comment]
谢谢大佬！
